version: "3"

services:
  fastapi-app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

  nextjs-app:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  db:
    image: postgres:13
    env_file:
      - postgres.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  node_modules:
